version: 0.2

phases:
  build:
    commands:
      - cd AWS/serverless-springboot2-example && mvn package -P assembly-zip
cache:
  paths:
    - '/root/.m2/**/*'
artifacts:
  files:
    - 'target/travelbot-0.0.1-SNAPSHOT-lambda-package.zip'