version: 0.2

phases:
  build:
    commands:
      - cd AWS/serverless-springboot2-example && mvn package -P assembly-zip
cache:
  paths:
    - '/root/.m2/**/*'
artifacts:
  files:
    - 'AWS/serverless-springboot2-example/target/serverless-springboot2-example-1.0-SNAPSHOT-lambda-package.zip'